### ISSUE TITLE
ปรับ recommended treatment 

### ISSUE THREAD

**Issue by buranee** [sirirajnicu/jaundice-assistant#3]
File birth admission screen
ตรง treatment ขอเปลี่ยนจาก
Line 22, 40, 52 "G6PD" เป็น "G6PD assay หากยังไม่เคยตรวจ"
Line 11, 17, 36 "CBC, blood smear, reti count, blood group, DAT"  เป็น "CBC, blood smear, reti count, blood group, DAT หากยังไม่เคยตรวจ"
Line 45 treatments = [
            "Admit to emergency neonatal units",
            "Double phototherapy",
            "TB/DB, albumin, CBC, blood smea, reti count",
            "Blood group, DAT",
            "Group match",
        ]
เปลี่ยนเป็น 
treatments = [
            "Admit ฉุกเฉินเพื่อ on phototherapy",
            "Double phototherapy",
            "เจาะเลือดหลัง admit และขอผลด่วน"
            "TB/DB, albumin",
            "CBC, blood smear, reti count, Blood group, DAT หากยังไม่เคยตรวจ",
            "Electrolyte หากทารกมี signs of dehydration",
            "Group match เตรียมทำ exchange transfusion โดยยังไม่ต้องตามเลือดมาที่หอผู้ป่วยทันทีให้รอผล TB/DB ก่อน",
            "NPO และให้ IV",
            "ปรึกษา fellow newborn เพื่อพิจารณาเตรียมทำ central line ตามความเหมาะสม" 
          ]

**Comment by nngerncham** [comment]
ส่วนที่เป็นภาษาไทยผมเก็บไว้ใส่หลังจากเปลี่ยน treatment จาก string เฉยๆ เป็น class Treatment นะครับ แต่เดี๋ยวแก้ treatment+แปลเป็นอังกฤษไว้ก่อนนะครับ

**Comment by buranee** [comment]
ได้จ้า
