### ISSUE TITLE
เพิ่ม recommendation ของ TSB value ใน no photo follow up

### ISSUE THREAD

**Issue by buranee** [sirirajnicu/jaundice-assistant#4]
File no photo follow up 
ใช้ค่า TCB value เป็นหลักจริง ๆ แล้วใช้ TSB value ก็ได้เหมือนกันใช้เกณฑ์เดียวกันเลย

**Comment by nngerncham** [comment]
เปลี่ยนชื่อ function ให้ใช้ได้ทั้งคู่ใน d4b05a1 นะครับ
