### ISSUE TITLE
เพิ่ม recommendation ของ TCB ลงใน file TSB and phototherypy

### ISSUE THREAD

**Issue by buranee** [sirirajnicu/jaundice-assistant#5]
สามารถใช้ TCB ในการติดตามได้ด้วยเลยต้อง add ค่า TCB ลงใน function ด้วย
สำหรับ finction tsb_lt_threshold_with_photo เกณฑ์สำหรับ TCB คือ
  1. TCB photo threshold - TCB patient <= 3 หรือ TCB patient >= 15 ให้ repeat TSB
  2. TCB photo threshold - TCB patient > 3 และ TCB patient < 15 ให้
        2.1 off photo หาก on single photo อยู่ และติดตามค่า TCB หรือ TSB ในอีก 12-24 ชั่วโมง ตาม อายุ neurotoxicity risk และ trajectory
        2.2 Single photo หาก on double photo อยู่ และติดตามค่า TCB หรือ TSB ในอีก 12-24 ชั่วโมง ตาม อายุ neurotoxicity risk และ trajectory
  4. TCB patient-TCB blood threshold>=-2  ให้ใช้ function
  def handle_tcb_geq_photo_threshold ที่อยู่ใน birth admission screening file

**Comment by nngerncham** [comment]
recommendation ที่ใช้ค่า tcb ตามมะอยู่ในไฟล์ birth_admission_screening ครับ เดี๋ยวแก้ชื่อให้ไฟล์ใหม่ให้มันเข้าใจง่ายกว่าเดิมนะครับ

**Comment by nngerncham** [comment]
เปลี่ยนชื่อไฟล์แล้วใน 9ef28b4 นะครับ
