### ISSUE TITLE
เปลี่ยน return ในกรณีที่ทารกอยู่ในช่วง 96 hr หลัง off photo

### ISSUE THREAD

**Issue by buranee** [sirirajnicu/jaundice-assistant#6]
จาก file tsb and phototherapy
def tsb_lt_threshold_no_photo(patient: Patient,
                              photo_threshold: float) -> str or list[str]:
    if is_within_96hrs_after_phototherapy(patient):
        return "Follow TSB/TCB according to rebound risk and trajectory"

ตรง return ขอเปลี่ยนให้มี conditions ซึ่งน้องป่านจะเขียนเป็น function ใหม่หรือเขียนยาว ๆ เป็น string ก็ได้ แต่ถ้าจะเขียน function ใหม่ต้องหาทางรู้ให้ได้ว่าคร้ังนี้ที่ทารก admit เป็น birth หรือ readmission อาจจะใช้เป็น input จากแพทย์ก็ได้นะ

return ดังนี้
1. Birth admission + GA<38 หรือ เมื่อเริ่ม photo อายุน้อยกว่า 48 hr ให้ติดตาม TSB/TCB ที่ 6-12 ชั่วโมงหลังหยุด phototherapy และอีกครั้งในวัดรุ่งขึ้น
2. Bith admission + GA>=38 และ อายุที่เริ่ม photo >= 48 ชั่วโมง ให้ติดตาม TSB/TCB ในวันรุ่งขึ้น
3. Readmission + เคย on photo ใน birth admission ติดตาม TSB/TCB ในวันรุ่งขึ้น
4.  Readmission + ไม่เคย on photo ใน birth admission ติดตาม TSB/TCB ในอีก 1-2 วันต่อมา

**Comment by nngerncham** [comment]
แก้แล้วใน 46f5f4b ครับ
