### ISSUE TITLE
งงตรงนี้นิดนึง

### ISSUE THREAD

**Issue by buranee** [sirirajnicu/jaundice-assistant#8]
def tsb_lt_threshold_with_photo(patient: Patient,
                                photo_threshold: float) -> str or list[str]:
    tsb_diff = photo_threshold - patient.tsb_value[-1]
    if tsb_diff < 0:
        return "No treatment"

ตรงนี้หมายความว่าถ้า TSB ของ patient มากกว่า phototherapy threshold แล้ว no treatment คือน้องป่านหมายความว่าก็ให้ phototherapy ต่อไปตามเดิมใช่เป่า
น้ากลัวจะงง แล้วก็กลัวว่าถ้าค่า TSB ของ patient มันเกิดเข้าใกล้เกณฑ์ blood exchange มากขึ้นมันจะอันตรายเปลี่ยนเป็นแบบนี้ได้มะ

1. ถ้า current TSB หรือ TCB - current blood exchange threshold>= -2 เอาแบบ def handle_tcb_geq_photo_threshold ที่อยู่ใน 
    birth admission screening file
2. ถ้า  current blood exchange threshold - current TSB หรือ TCB<  previous blood exchange threshold - previous TSB หรือ TCB 
    2.1 ทารกกำลัง on single phototherapy อยู่ ให้เพิ่มเป็น double phototherapy และติดตาม TSB หรือ TCB ในอีก 4-6 ชั่วโมง
    2.2 ทารก on double phototherapy อยู่แล้ว ให้ปรับประสิทธิภาพของการ phototherapy ให้ดีขึ้น
3. ถ้า  current blood exchange threshold - current TSB หรือ TCB >  previous blood exchange threshold - previous TSB หรือ TCB 
   ให้ on phototherapy ชนิดเดิมต่อไป และติดตาม TSB หรือ TCB ใน 12-24 ชั่วโมง ตามอายุ neurotoxicity risk และ trajectory

**Comment by nngerncham** [comment]
โค้ดสำหรับเวลา TSB level >= photo threshold แล้วต้องไปเทียบกับ proximity of TSB level to exchange transfusion threshold ยังไม่ได้เขียน เดี๋ยวเขียนแล้วจะมา mention ใน comment ถัดไปครับ

**Comment by nngerncham** [comment]
fixed in 90c710f57ddc2a784be4007488fdca2aafcef083
